# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Chatter"); Pkg.test("Chatter"; coverage=true)'
after_success:
  # Push coverage results to CodeCov
  - julia -e 'cd(Pkg.dir("Chatter")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  # Build documentation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Chatter")); include(joinpath("docs", "make.jl"))'
